/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_diy_simulator_RemovebackgroundActivity */

#ifndef _Included_com_example_diy_simulator_RemovebackgroundActivity
#define _Included_com_example_diy_simulator_RemovebackgroundActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_diy_simulator_RemovebackgroundActivity_PERMISSIONS_REQUEST_CODE
#define com_example_diy_simulator_RemovebackgroundActivity_PERMISSIONS_REQUEST_CODE 1000L
/*
 * Class:     com_example_diy_simulator_RemovebackgroundActivity
 * Method:    ConvertRGBtoGray
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_example_diy_1simulator_RemovebackgroundActivity_ConvertRGBtoGray
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
